apiVersion: apps/v1
kind: Deployment
metadata:
  name: model1
  labels:
    app: model1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model1
  template:
    metadata:
      labels:
        app: model1
    spec:
      containers:
      - name: model1
        image: land95/mlflow-model:0.1
        ports:
        - containerPort: 5001